import re
from typing import Annotated, Generic, Literal, Optional, TypeVar
from pydantic import BaseModel, ConfigDict, Field, field_validator

T = TypeVar("T")

ServiceErrorType = Literal[
    "timeout",
    "network_error",
    "auth_error",
    "rate_limited",
    "not_found",
    "server_error",
    "parse_error",
    "service_disabled",
]


class ServiceResult(BaseModel, Generic[T]):
    available: bool
    data: Optional[T] = None
    error_type: Optional[ServiceErrorType] = None
    detail: Optional[str] = None


# ---------- Triage classification ----------
EmergencyCategory = Literal[
    "flooding",
    "electrocution",
    "injury",
    "snakebite",
    "cyclone",
    "structural_damage",
    "accident",
    "unclassified",
]

TriageTier = Literal[1, 2, 3]


class TriageResult(BaseModel):
    """Output of the three-tier triage classification cascade.

    Determines *what type* of incident this is.
    Never determines severity — that is the exclusive domain of the
    deterministic weather/risk score (Principle 2).
    """
    category: EmergencyCategory
    confidence: float = Field(..., ge=0.0, le=1.0, description="0.0–1.0")
    tier: TriageTier = Field(..., description="1=keyword, 2=embedding, 3=LLM fallback")
    matched_rule_or_example: Optional[str] = Field(
        None,
        description="Human-readable label of the matched keyword/phrase or example sentence.",
    )
    explanation: str = Field(..., description="Why this category was chosen (deterministic for Tiers 1–2).")


# ---------- Structured Action Planning (Step 5) ----------
class ActionPlan(BaseModel):
    """Strictly structured emergency action plan generated by LLM or deterministic fallback.

    The LLM acts as an action-planning assistant only.
    It MUST NOT contain: severity, emergency_level, triage category,
    weather risk score, confidence score, routing decisions, hospital
    recommendations, or arbitrary URLs.
    """
    model_config = ConfigDict(extra="ignore")

    immediate_actions: list[Annotated[str, Field(max_length=500)]] = Field(
        ..., min_length=1, max_length=15, description="Prioritized immediate safety steps"
    )
    safety_warnings: list[Annotated[str, Field(max_length=500)]] = Field(
        default_factory=list, max_length=15, description="Things NOT to do / critical warnings"
    )
    when_to_seek_help: list[Annotated[str, Field(max_length=500)]] = Field(
        default_factory=list, max_length=15, description="Specific triggers requiring immediate escalation"
    )
    questions_to_ask_user: list[Annotated[str, Field(max_length=500)]] = Field(
        default_factory=list, max_length=10, description="Clarifying questions if genuinely necessary"
    )
    emergency_contacts: list[Annotated[str, Field(max_length=200)]] = Field(
        default_factory=list, max_length=10, description="Trusted emergency helpline numbers"
    )
    explanation: Annotated[str, Field(max_length=1000)] = Field(
        ..., description="Brief, concise rationale for the recommended actions"
    )

    @field_validator("immediate_actions", "safety_warnings", "when_to_seek_help", "questions_to_ask_user", mode="after")
    @classmethod
    def reject_urls_in_lists(cls, v: list[str]) -> list[str]:
        url_pattern = re.compile(r"(https?://\S+|www\.\S+)", re.IGNORECASE)
        for item in v:
            if url_pattern.search(item):
                raise ValueError(f"Action plan item cannot contain arbitrary URLs: {item}")
        return v

    @field_validator("explanation", mode="after")
    @classmethod
    def reject_urls_in_explanation(cls, v: str) -> str:
        url_pattern = re.compile(r"(https?://\S+|www\.\S+)", re.IGNORECASE)
        if url_pattern.search(v):
            raise ValueError(f"Action plan explanation cannot contain arbitrary URLs: {v}")
        return v


class ActionPlanContext(BaseModel):
    """Structured context assembled by deterministic systems and passed to action planner."""
    model_config = ConfigDict(extra="ignore")

    user_description: str
    triage_category: EmergencyCategory
    weather_risk: Optional[dict] = None
    location_context: Optional[dict] = None
    available_services: Optional[dict] = None
    trusted_contacts: Optional[list[str]] = None


# ---------- Confidence Aggregation (Step 6) ----------
ConfidenceLevel = Literal["high", "medium", "low"]
ActionPlanSource = Literal["deterministic", "groq"]


class ConfidenceResult(BaseModel):
    """Centralized aggregated confidence assessment following weakest-link principle.

    All confidence values are strictly between 0.0 and 1.0.
    The LLM has zero authority over confidence or severity.
    """
    model_config = ConfigDict(extra="forbid")

    overall_confidence: float = Field(..., ge=0.0, le=1.0, description="Weakest-link overall confidence score")
    confidence_level: ConfidenceLevel = Field(..., description="Categorical confidence: high >= 0.80, medium >= 0.50, low < 0.50")
    triage_confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence of triage classification")
    weather_confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence of weather signal availability")
    action_plan_confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in action-plan provenance (deterministic=1.0, groq=0.35)")
    limiting_factor: str = Field(..., description="Subsystem responsible for capping overall confidence")


# ---------- Assessment (Responder / "Get Help Now") ----------
class AssessmentRequest(BaseModel):
    description: str = Field(..., description="What the user typed or a preset filled in")
    city: str | None = Field(None, description="Optional area/city; falls back to server default")
    lat: float | None = None
    lon: float | None = None
    language: str = Field("English", description="Reply language, e.g. English / Telugu / Hindi")
    request_sos: bool = Field(False, description="Explicit user request to trigger SOS")
    situation: str | None = Field(None, description="Optional situation description for SOS")


class AssessmentResponse(BaseModel):
    emergency_level: str          # e.g. "Critical" | "High" | "Moderate" | "Low"
    whats_happening: str
    immediate_first_aid: list[str]
    what_not_to_do: list[str]
    call_these_services: list[str]
    things_to_carry: list[str]
    nearby_help: list[dict]       # [{"name": ..., "url": ...}]
    raw_text: str                 # full model output, for debugging / fallback display


# ---------- Chat (multi-turn Responder) ----------
class ChatMessage(BaseModel):
    role: str   # "user" | "assistant"
    text: str


class ChatRequest(BaseModel):
    history: list[ChatMessage]
    message: str
    city: str | None = None


class ChatResponse(BaseModel):
    reply: str


# ---------- Weather / risk (Sentinel) ----------
class WeatherSummary(BaseModel):
    temp_c: float
    condition: str
    rain_mm_last_hour: float
    alert_active: bool
    alert_headline: str | None = None


class RiskScore(BaseModel):
    score: int                    # 0-100
    level: str                    # "watch" | "warning" | "critical" | "safe"
    rainfall_intensity_pct: int
    drainage_capacity_pct: int    # placeholder factor — see risk_service.py


# ---------- Hospitals / Shelters (Wayfinder) ----------
class HospitalOut(BaseModel):
    name: str
    lat: float
    lon: float
    distance_km: float | None = None
    address: str | None = None
    source: str = "google_places"


class ShelterOut(BaseModel):
    id: str
    name: str
    capacity: int
    occupied: int
    address: str | None = None
    lat: float | None = None
    lon: float | None = None
    source: str = "manual"        # flag that this is admin-entered, not a live feed


# ---------- Community reports ----------
class ReportIn(BaseModel):
    area: str
    message: str
    reporter_name: str | None = None


class ReportOut(BaseModel):
    id: str
    area: str
    message: str
    verified: bool
    created_at: str


# ---------- SOS ----------
SosNotificationStatus = Literal[
    "pending_notification",
    "notification_accepted",
    "notification_failed",
    "notification_disabled",
]


class SosRequest(BaseModel):
    lat: float
    lon: float
    situation: str | None = None


class SosEventRecord(BaseModel):
    event_id: str
    created_at: str
    updated_at: str
    latitude: float
    longitude: float
    situation: Optional[str] = None
    notification_status: SosNotificationStatus
    message_id: Optional[str] = None
    error_detail: Optional[str] = None


class SosResponse(BaseModel):
    event_id: Optional[str] = None
    status: Literal["recorded", "degraded"]
    notification_status: Literal[
        "notification_accepted",
        "notification_failed",
        "notification_disabled",
    ]
    maps_link: str
    message: str


# ---------- Unified Emergency Orchestrator Result (Step 7) ----------
class AssessmentResult(BaseModel):
    """Unified emergency assessment result assembled by the Emergency Orchestrator (Step 7).

    Coordinates triage category, deterministic weather risk, structured action plan,
    weakest-link confidence, optional hospital list, and optional explicit SOS response.
    Also provides legacy fields for backward compatibility with existing clients.
    """
    model_config = ConfigDict(extra="ignore")

    # Structured Orchestration Data
    triage: TriageResult
    weather: Optional[dict] = None
    action_plan: ActionPlan
    confidence: ConfidenceResult
    hospitals: list[HospitalOut] = Field(default_factory=list)
    sos: Optional[SosResponse] = None
    service_status: dict[str, str] = Field(default_factory=dict)

    # Backward-Compatible Legacy Fields
    emergency_level: str = "Moderate"
    whats_happening: str = ""
    immediate_first_aid: list[str] = Field(default_factory=list)
    what_not_to_do: list[str] = Field(default_factory=list)
    call_these_services: list[str] = Field(default_factory=list)
    things_to_carry: list[str] = Field(default_factory=list)
    nearby_help: list[dict] = Field(default_factory=list)
    raw_text: str = ""


# ---------- Push notification device registration ----------
class DeviceTokenIn(BaseModel):
    token: str
